services:
  logs-monitor:
    build:
      context: .
      network: host
    image: logs-monitor:latest
    container_name: logs-monitor
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - global-link
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.logs-monitor.rule=Host(`${DOMAIN}`) && PathPrefix(`/logs-monitor`)"
      - "traefik.http.middlewares.logs-monitor-strip.stripprefix.prefixes=/logs-monitor"
      - "traefik.http.routers.logs-monitor.middlewares=logs-monitor-strip@docker"
      - "traefik.http.routers.logs-monitor.entrypoints=websecure"
      - "traefik.http.routers.logs-monitor.tls=true"
      - "traefik.http.services.logs-monitor.loadbalancer.server.port=80"

networks:
  global-link:
    external: true
  proxy:
    external: true
